# Generated by Django 4.2.5 on 2023-09-04 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estadios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RedFox.time')),
            ],
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('preco', models.FloatField(max_length=10000)),
                ('quantidade', models.IntegerField(default=1)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RedFox.categoria')),
                ('estadios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RedFox.estadios')),
                ('jogos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RedFox.jogos')),
                ('time', models.ManyToManyField(related_name='+', to='RedFox.time')),
            ],
        ),
        migrations.AddField(
            model_name='estadios',
            name='jogos',
            field=models.ManyToManyField(related_name='+', to='RedFox.jogos'),
        ),
    ]
